###
GET http://localhost:3000/api/get-posts

###
POST http://localhost:3000/api/create-posts
content-type: "application/json"

{
    "text": "textt",
    "name": "tuguldur"
}
###
DELETE http://localhost:3000/api/delete-posts?_id=64951aa9af6e49e67b45b425

###
PUT   http://localhost:3000/api/uptade-posts?_id=64951304b4552e3290373afd
